services:
  - type: web
    name: diagramador-v12-web
    env: python
    plan: free
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --timeout 600 --bind 0.0.0.0:$PORT
    autoDeploy: true
